# Generated by Django 2.2.6 on 2021-04-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='recipes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
