# Generated by Django 2.2.6 on 2021-04-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_recipe_directions'),
        ('jedzonko', '0003_auto_20210428_1338'),
    ]

    operations = [
    ]
