# Generated by Django 2.2.6 on 2021-04-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_merge_20210429_1101'),
        ('jedzonko', '0004_merge_20210429_1105'),
    ]

    operations = [
    ]
