# Generated by Django 2.2.6 on 2021-04-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_auto_20210429_1949'),
        ('jedzonko', '0007_auto_20210429_2223'),
    ]

    operations = [
    ]
