# Generated by Django 2.2.6 on 2021-05-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0008_merge_20210430_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='order',
            field=models.CharField(max_length=126, unique=True),
        ),
    ]
