# Generated by Django 2.2.6 on 2021-05-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0009_auto_20210505_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='order',
            field=models.CharField(max_length=126),
        ),
        migrations.AlterUniqueTogether(
            name='recipeplan',
            unique_together={('order', 'day_name')},
        ),
    ]
