# Generated by Django 2.2.6 on 2021-05-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_auto_20210505_0946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeplan',
            unique_together={('order', 'day_name', 'meal_name')},
        ),
    ]
